### ISSUE TITLE
Not working with fresh install

### ISSUE THREAD

**Issue by Saturate** [nevir/groc#154]
It's not working with a fresh install:

```
C:\Users\CurrentUser\AppData\Roaming\npm\node_modules\groc\node_modules\jade\lib\runtime.js:202
  throw err;
        ^
Error: Jade:1
  > 1| !!! 5
    2| html(lang="en")
    3|   head
    4|     title= pageTitle

`!!!` is deprecated, you must now use `doctype`
    at Object.Lexer.doctype (C:\Users\CurrentUser\AppData\Roaming\npm\node_modules\groc\node_modules\jade\lib\lexer.js:248:13)
    at Object.Lexer.next (C:\Users\CurrentUser\AppData\Roaming\npm\node_modules\groc\node_modules\jade\lib\lexer.js:833:15)
    at Object.Lexer.lookahead (C:\Users\CurrentUser\AppData\Roaming\npm\node_modules\groc\node_modules\jade\lib\lexer.js:113:46)
    at Parser.lookahead (C:\Users\CurrentUser\AppData\Roaming\npm\node_modules\groc\node_modules\jade\lib\parser.js:111:23)
    at Parser.peek (C:\Users\CurrentUser\AppData\Roaming\npm\node_modules\groc\node_modules\jade\lib\parser.js:88:17)
    at Parser.parse (C:\Users\CurrentUser\AppData\Roaming\npm\node_modules\groc\node_modules\jade\lib\parser.js:126:26)
    at parse (C:\Users\CurrentUser\AppData\Roaming\npm\node_modules\groc\node_modules\jade\lib\jade.js:95:62)
    at Object.exports.compile (C:\Users\CurrentUser\AppData\Roaming\npm\node_modules\groc\node_modules\jade\lib\jade.js:152:9)
    at new Default (C:\Users\CurrentUser\AppData\Roaming\npm\node_modules\groc\lib\styles\default.coffee:37:32)
    at Project.module.exports.Project.generate (C:\Users\CurrentUser\AppData\Roaming\npm\node_modules\groc\lib\project.coffee:40:15)
    at Object.module.exports.CLI (C:\Users\CurrentUser\AppData\Roaming\npm\node_modules\groc\lib\cli.coffee:201:22)
    at Object.<anonymous> (C:\Users\CurrentUser\AppData\Roaming\npm\node_modules\groc\bin\groc:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

```

If I fix this manually I get another error:

```
    ! Rendering documentation template for D:\PathToProject\dist\doc\index.html failed: Cannot call method 'call' of un
defined on line 1

Warning: Cannot call method 'call' of undefined on line 1 Use --force to continue.
TypeError: Cannot call method 'call' of undefined on line 1
    at eval (eval at <anonymous> (D:\PathToProject\node_modules\grunt-groc\node_modules\groc\node_modules\jade\lib\
jade.js:152:8), <anonymous>:7:15)
    at Default.templateFunc (D:\PathToProject\node_modules\grunt-groc\node_modules\groc\node_modules\jade\lib\jade.
js:153:35)
    at D:\PathToProject\node_modules\grunt-groc\node_modules\groc\lib\styles\base.coffee:108:24
    at D:\PathToProject\node_modules\grunt-groc\node_modules\groc\node_modules\fs-tools\lib\fs-tools.js:485:9
    at Object.oncomplete (fs.js:107:15)
```

I'm not sure what to do.

**Comment by brianbouril** [comment]
Saturate,

This was fixed by this pull request ( https://github.com/nevir/groc/pull/153 ) but not merged in yet.

You can apply the fix manually pretty easily if you want.

In this file: groc/lib/styles/default/docPage.jade

Change this:
!!! 5

To this:
doctype html

**Comment by Saturate** [comment]
I did this, but then I get the second error!
