### ISSUE TITLE
Error when execute groc

### ISSUE THREAD

**Issue by luispigu** [nevir/groc#78]
Hi,
I try to use groc on my Mac OS X but when i execute groc on terminal, there are error messages like below.
I tried to use Ubuntu to execute groc but it generated same error messages.

Anyone who knows a reason of this message, please help me.
Thanks

::Error Messages::

/usr/local/lib/node_modules/groc/node_modules/autorequire/lib/loader.js:109
      throw new Error("No autorequire.Loader behavior defined for node " + pro
            ^
Error: No autorequire.Loader behavior defined for node v0.10.1
    at /usr/local/lib/node_modules/groc/node_modules/autorequire/lib/loader.js:109:13
    at Object.<anonymous> (/usr/local/lib/node_modules/groc/node_modules/autorequire/lib/loader.js:111:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/groc/node_modules/autorequire/lib/loader.js:120:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/groc/node_modules/autorequire/lib/autorequire.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/groc/node_modules/autorequire/lib/autorequire.js:88:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/groc/index.js:5:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/groc/bin/groc:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

**Comment by thiagomata** [comment]
Same error for me.

**Comment by curran** [comment]
I am also getting this error. This is stopping me from using Groc.

**Comment by nevir** [comment]
Sorry folks, for the moment groc is not compatible with node 0.10.  I'm working on a fix, but haven't had much time to devote to it

**Comment by dmitrye** [comment]
as someone else pointed out (in another thread) you can modify the loader.js under .../groc/node_modules/autorequire/lib/ folder so that === 8 is instead >= 8 for the node server version.

**Comment by nevir** [comment]
This is fixed in `v0.4.0`
